box_L 34.99514024
rc 2.5
skin 0.3
dt 0.001
temperature 1.0
gamma 1.0
seed 42
nsteps 100
thermo 1 100 thermo.dat
rg 0 100 rg.dat
stress 0 100 stress_acf.dat
dump_freq 0
natoms 30000
ntypes 1
lj 0 0 1.0 1.0
bond_type 0 30.0 1.5 1.0 1.0
angle_type 0 5.0 180.0
lammps_data_file /home/zhenghaowu/fastMD/data/input_000_minimized.data
